In [3]:
#dictionary
dict1={
        "st":"sachin tendulkar",
        "msd":"mahendra singh dhoni",
        "runs":10000  }
print(dict1)
print(dict1["runs"])
for x in dict1:
    print(x)
for x in dict1:
    print(dict1[x])
for x in dict1:
    print(x,":",dict1[x])

{'st': 'sachin tendulkar', 'msd': 'mahendra singh dhoni', 'runs': 10000}
10000
st
msd
runs
sachin tendulkar
mahendra singh dhoni
10000
st : sachin tendulkar
msd : mahendra singh dhoni
runs : 10000


In [6]:
#inserting item in dictionary
dict1["sv"]="sourav ganguly"
print(dict1)

{'st': 'sachin tendulkar', 'msd': 'mahendra singh dhoni', 'runs': 10000, 'sv': 'sourav ganguly'}


In [9]:
#updating value in dictionary
dict1["runs"]=34500
print(dict1)
print(dict1["runs"])
print(len(dict1))

{'st': 'sachin tendulkar', 'msd': 'mahendra singh dhoni', 'runs': 34500, 'sv': 'sourav ganguly'}
34500
4


In [10]:
#remove items from dict
dict1={
        "st":"sachin tendulkar",
        "msd":"mahendra singh dhoni",
        "runs":10000  }
print(dict1)
var=dict1.pop("runs")
print(dict1)
print(var)
var1=dict1.popitem()
print(dict1)
print(var)

{'st': 'sachin tendulkar', 'msd': 'mahendra singh dhoni', 'runs': 10000}
{'st': 'sachin tendulkar', 'msd': 'mahendra singh dhoni'}
10000
{'st': 'sachin tendulkar'}
10000


In [12]:
#creating a tuple
tuple1=("sachin","msd","sourav")
print(tuple1[0],tuple1[1])
for x in tuple1:
    print(x)

sachin msd
sachin
msd
sourav


In [13]:
#create a tuple or tuple packing
tuplex=4,8,4
print(tuplex)
n1,n2,n3=tuplex
#UNPACK A TUPLE IN VARIABLES
print(n1+n2+n3)

(4, 8, 4)
16


In [15]:
#creating a set
days=set(["mon","tue","wed","thu","fri","sat","sun","sun"])
months={"jan","feb","mar"}
dates={21,22,3}
print(days)
print(months)
print(dates)
print(type(dates))

{'tue', 'mon', 'fri', 'thu', 'sun', 'sat', 'wed'}
{'feb', 'mar', 'jan'}
{3, 21, 22}
<class 'set'>


In [16]:
#adding items to a set
#set is immutable here
days=set(["mon","tue","wed","thu","fri","sat"])
print(id(days))
days.add("abs")
print(id(days))
print(days)
days={"cde"}
print(id(days))

777749223016
777749223016
{'tue', 'mon', 'fri', 'thu', 'abs', 'sat', 'wed'}
777749224136


In [18]:
#removing from a set
print(id(days))
days=set(["mon","tue","wed","thu","fri","sat"])
days.discard("sun")
print(days)

777749223016
{'tue', 'mon', 'fri', 'thu', 'sat', 'wed'}


In [22]:
#union of set
daysA=set(["wed","sun"])
daysB=set(["mon","tue","wed","thu","fri","sat"])
alldays=daysA|daysB
print(alldays)
#intersection of set
alldays=daysA & daysB
print(alldays)

{'tue', 'mon', 'fri', 'thu', 'sun', 'sat', 'wed'}
{'wed'}


In [24]:
import numpy as np
#1D array
arr1=np.array([1,2,3])
print(arr1)
print(type(arr1))
print(arr1.dtype)
print(arr1[0])

[1 2 3]
<class 'numpy.ndarray'>
int32
1


In [27]:
#nD array
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2[1,1],arr2[0,2])

[[1 2 3]
 [4 5 6]]
5 3


In [28]:
arr2=np.array([(9),(2)])
print(arr2)
print(arr2.ndim)
arr2=np.array([(9,),(2,)])
print(arr2)
print(arr2.ndim)

[9 2]
1
[[9]
 [2]]
2


In [29]:
import numpy as np
#data tyoe
arr3=np.array([9,2],dtype=float)
print(arr3)
print(arr3.dtype)

[9. 2.]
float64


In [36]:
#shape returns tuple consisting of array dimensions
arr1=np.array([[10,20],[30,40],[30,40]])
print("array shape is :",arr1.shape)
print("array is:",arr1)

array shape is : (3, 2)
array is: [[10 20]
 [30 40]
 [30 40]]


In [34]:
#resize the shape
arr1=np.array([[10,20,30],[30,40,50]])
print("array shape is :",arr1.shape)
arr1.shape=(3,2)
print("array shape is :",arr1.shape)
print("array is:",arr1)

array shape is : (2, 3)
array shape is : (3, 2)
array is: [[10 20]
 [30 30]
 [40 50]]


In [38]:
#resizing through reshape()
arr2=np.array([[10,23,30,40],[30,40,50,60]])
print(arr2)
b=arr2.reshape(4,2)
print("array shape is:",arr2.shape)
print("array is :",b)

[[10 23 30 40]
 [30 40 50 60]]
array shape is: (2, 4)
array is : [[10 23]
 [30 40]
 [30 40]
 [50 60]]


In [42]:
#array creation routines
#empty() creates an uninitialized array
arr1=np.array([3,2],dtype=int)
print("filled with random values:",arr1) #filled with random values

#Zeros creates an array filled with zeroes
arr2=np.zeros([3,2])
print("filled with 0 ints:",arr2)

#ones 
arr3=np.ones([3,2])
print("filled with one floats:",arr3)

filled with random values: [3 2]
filled with 0 ints: [[0. 0.]
 [0. 0.]
 [0. 0.]]
filled with one floats: [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [43]:
#filling nd array from existing data structures
list1=[1,2,3,4]
arr1=np.array(list1)
print(type(list1))
print(list1)

<class 'list'>
[1, 2, 3, 4]


In [46]:
#ndarray from tuple
tup1=(1,2,3)
arr3=np.array(tup1)
print(arr3)

#ndarray from a list of tuple
list1=[(1,2,3),(4,5,6)]
arr4=np.array(list1)
print("dim of array:",arr4.ndim)
print("array from list of tuples:",arr4)

[1 2 3]
dim of array: 2
array from list of tuples: [[1 2 3]
 [4 5 6]]


In [47]:
#fromiter--ndarray from iterator object
list1=range(5)
x=iter(list1)#returns iterator object

arr5=np.fromiter(x,dtype=float)
print("array from iterator object:",arr5)


array from iterator object: [0. 1. 2. 3. 4.]
