In [6]:
import numpy as np
#arange--evenly spaced nums from range
arr1=np.arange(10) #uper bound not included
print(arr1)

arr2=np.arange(10,dtype=float)
print(arr2)

arr3=np.arange(2,10,2)
print(arr3) #start,stop,step

#linspace--instead of step,the no. of intervel is specified
arr4=np.linspace(2,10,3,endpoint=False,dtype=int) #endpoint is to include the upperbound
print("arr4)

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[2 4 6 8]
[2 4 7]


In [9]:
import numpy as np
arr1=np.arange(10)

print("2.after slicing :",arr1[2:9:1])
print("3.after slicing :",arr1[2:])

#slicing for nd array
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("after slicing:",arr2[:,1:])

#using ellipsis
arr4=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("after slicing:",arr4[...,1])
print("after slicing:",arr4[2,...]) #its same as print(arr[2])
print("after slicing:",arr4[...,1:])


2.after slicing : [2 3 4 5 6 7 8]
3.after slicing : [2 3 4 5 6 7 8 9]
after slicing: [[2 3]
 [5 6]
 [8 9]]
after slicing: [2 5 8]
after slicing: [7 8 9]
after slicing: [[2 3]
 [5 6]
 [8 9]]


In [11]:
 #integer indexing
arr5=np.array([[1,2,3],[4,5,6],[7,8,9]])
y=arr5[[0,1,2],[1,0,2]]
print(y)

arr6=np.array([[1,2,3],[4,5,5],[6,7,8]])
y=arr6[(0,2),(0,2)]
print(y)

[2 4 9]
[1 8]


In [12]:
#broadcasting when operations with multiple arrays with shape
arr7=np.array([[10,20,30],[4,5,6]])
arr8=np.array([[40,3,20],[7,6,5]])
print(arr7*arr8)

[[400  60 600]
 [ 28  30  30]]


In [13]:
#smaller array is broadcasted to larger array
arr8=np.array([[1,1,1],[20,30,40],[2,3,4]])
arr9=np.array([1,2,3])
print(arr8+arr9)

[[ 2  3  4]
 [21 32 43]
 [ 3  5  7]]


In [16]:
#transposing an array & then iterating
arr1=np.array([[1,1,1],[20,30,40],[2,3,4]])
print(arr1.T)

[[ 1 20  2]
 [ 1 30  3]
 [ 1 40  4]]


In [18]:
#concatenate
arr1=np.array([[2,3],[4,5]])
arr2=np.array([[6,7],[8,9]])
resarr=np.concatenate((arr1,arr2)) #default axis=0
print("concatenate along 0 axis:",resarr)
resarr=np.concatenate((arr1,arr2),axis=1)
print("concatenate along 1 axis:",resarr)

concatenate along 0 axis: [[2 3]
 [4 5]
 [6 7]
 [8 9]]
concatenate along 1 axis: [[2 3 6 7]
 [4 5 8 9]]


In [13]:
#split
arr3=np.arange(9)
print(arr3)
arr4=np.split(arr3,3)
print(arr4)

[0 1 2 3 4 5 6 7 8]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [16]:
#append elements
arr4=np.arange(9)
arr4=arr4.reshape(3,3)
print("before appending:",arr4)
arr5=np.append(arr4,[10,11,12])
print("after appending:",arr5)
arr6=np.append(arr4,[[10,11,12],[13,14,15],[16,17,18]],axis=1)
print("at 1 axis",arr6)
arr6=np.append(arr4,[[10,11,12]],axis=0)
print("at 0 axis",arr6)

before appending: [[0 1 2]
 [3 4 5]
 [6 7 8]]
after appending: [ 0  1  2  3  4  5  6  7  8 10 11 12]
at 1 axis [[ 0  1  2 10 11 12]
 [ 3  4  5 13 14 15]
 [ 6  7  8 16 17 18]]
at 0 axis [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [10 11 12]]


In [12]:
arr4=np.arange(9)
arr4=arr4.reshape(3,3)
arr5=np.insert(arr4,3,199)
print(arr5)
arr6=np.insert(arr4,3,[11],axis=0)
print(arr6)
arr7=np.insert(arr4,3,[11],axis=1)
print(arr7)


[  0   1   2 199   3   4   5   6   7   8]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [11 11 11]]
[[ 0  1  2 11]
 [ 3  4  5 11]
 [ 6  7  8 11]]


In [15]:
#delete method
arr4=np.arange(9)
arr4=arr4.reshape(3,3)
arr10=np.delete(arr4,3)
print("array flattened before deleting as axis parameter not passed:",arr10)
arr11=np.delete(arr4,2,axis=0)
print("along 0 axis:",arr11)
print(arr4)
arr11=np.delete(arr4,2,axis=1)
print("along 1 axis:",arr11)
print(arr4)

array flattened before deleting as axis parameter not passed: [0 1 2 4 5 6 7 8]
along 0 axis: [[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
along 1 axis: [[0 1]
 [3 4]
 [6 7]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [27]:
arr=np.array([[89,76,93],[21,15,8],[100,110,98]])
print(arr)
arr0=np.mean(arr,axis=1)
print("applying mean function along 0 axis:",arr0)
arr1=np.sort(arr0)
print(arr1)
for i in arr1:
    for j in arr:
        if i==np.mean(j):
            print(j)
        

[[ 89  76  93]
 [ 21  15   8]
 [100 110  98]]
applying mean function along 0 axis: [ 86.          14.66666667 102.66666667]
[ 14.66666667  86.         102.66666667]
[21 15  8]
[89 76 93]
[100 110  98]
